### ISSUE TITLE
Protocol buffer split is not working on UNI2/3 using USB serial cable

### ISSUE THREAD

**Issue by abdavid** [patstave/Node-FlexitCS60-RS485#1]
I tilfelle kan jeg muligens bistå med det :) 

Jeg kom over dine posts på hjemmeautomasjon ang Flexit + HA og planlegger å følge den samme ruta. Svært elegant løsning med Elfin EW11 du har funnet 👍 

Driver og skal sette den opp her nå de neste dagene. Har du gjort endringer på switches ift master/slave konfigurasjon med EW11?

**Comment by abdavid** [comment]
Kan vi forresten bruke modbus registeret til noe i denne sammenhengen? https://www.flexit.no/globalassets/catalog/documents/man_111824en_3510.pdf

**Comment by patstave** [comment]
Hei @abdavid !
EW11 fungerer out of the box. Trenger kun å sette opp WiFi-innstillingene.
Det modbus-registeret du henviser til er det samme jeg har brukt. De aller fleste av disse datapunktene bør eksistere. Dog er det ikke noen sammenheng med rekkefølge på internbussen og rekkefølgen på modbus-registrene. Om du har en CI600 å låne hadde det hjulpet enormt. Jeg har ikke gjort noe mer jobb på dette pga. mangelen på panelet. Med kun CI60 blir det utrolig tungvindt å holde på.

**Comment by abdavid** [comment]
Rart. Sliter litt med få ut data :/ Har dog ikke koblet meg på med EW11 og et styrepanel samtidig. Hijacket bare min CI600 sin RJ12 kontakt. Har klart å få noe ut, men svært begrenset og ikke konsistent, og ikke noe som lot seg oversette til HA sensor data i hvert fall. Virker ikke som om det blir rapportert tilstand der i intervaller slik jeg hadde forventet. 

Jeg kan godt låne deg min. Jeg har en CI60 liggende i tillegg jeg kan bruke i mellomtiden. Send meg dine detaljer på patstave[at]abdavid.net så kan vi ta detaljer om forsendelse der.

**Comment by patstave** [comment]
Pass på at du har rett polaritet på A og B-pinnene. Prøv å veksle! Jeg hadde problemer med å bruke RJ12 på panelet, prøv den inne i ventilasjonsanlegget. Fant også ut at pinnene på panelet er motsatt polaritet av den inne i i anlegget. Jeg sender deg mail.

**Comment by abdavid** [comment]
> Fant også ut at pinnene på panelet er motsatt polaritet av den inne i i anlegget. 

Impliserer det egentlig at jeg muligens ikke kan bruke hyllevare RJ12 kabler? ala denne https://www.kjell.com/no/produkter/hjem-fritid/fasttelefoni/installasjon/telefonkabler/modulkabler/modulkabel-rj12-66-3-m-p38406 ?

**Comment by patstave** [comment]
Du må krysskoble kabelen uansett ja. Det passer ikke med ferdig koblet kabel uansett. Se pinout på readme i repoet.

**Comment by abdavid** [comment]
Alright, da ser jeg på det i mellomtiden. 

Ref det du skrev tidligere med å legge modbus registeret til grunn for den nåværende implementasjonen, kunne det ha hjulpet noe om vi fikk tak i registeret for internbussen? Er jo evt bare å spørre pent? 😄

**Comment by abdavid** [comment]
@patstave da har jeg fått ordnet kabel og jeg får en stream med data fra CS60en, usikker på om det er noen andre forskjeller her, men alle meldingene jeg mottar går rett i `undefined` topicen. Er det som forventet? 

f.eks

```js
{
  payload: array[510],
  topic: undefined,
  header: array[4],
  bufferSize: 510,
 _msgId: "4db923977486204c"
}
```

**Comment by patstave** [comment]
Har du prøvd begge polaritetene med kabelen? Du vil få data uansett, men om polaritetene er feil vil det bli "garbled". Også viktig at du setter rett databit/startbit/stoppbit. Når det gjelder tilgang til registeret på internbussen så hadde det vært helt fantastisk ja. Men har nok en mistanke om at man må kjenne rett person i så fall. Men lov å prøve er det jo alltids 🫰

**Comment by patstave** [comment]
Har du UNI2 eller ett annet aggregat?

**Comment by abdavid** [comment]
Mener det skal være koblet riktig ift pinout du har liggende i README og manualen til EW11 😅 Dog ikke min sterkeste side dette, så kan se over i morgen.

Mener det er UNI3 eller UNI4 jeg har, men kontrolleren er jeg ganske sikker på er en CS60 da manualen til den fulgte med huset. 

En ting jeg har lagt merke til i dataene jeg mottar er at bufferSize alltid er 510. Den er 512 fra EW11, så splices der bort de to første punktene i bufferen og assigner det til bufferSize. Mulig det er relater til det du skriver om at jeg bør dobbeltsjekke kablingen.

Ift databit/startbit/stoppbit så er de satt til samme som i READMEen

**Comment by abdavid** [comment]
Da har jeg snudd om på A og B og observerer nå at størrelsen på meldingene som kommer varierer nå i større grad enn før. Det er ikke 510 (512) i bufferSize lengre, men nå er det;

172,
173,
174,
193
196
344
345
 
og flere. 

Det er kanskje mer korrekt? Fortsatt ser jeg ingen av meldingene får assignet et topic, men det er da kanskje noe med UNI2 vs UNI3?

**Comment by patstave** [comment]
Antakelig er 512 bytes kapasiteten til serieport-adapteret ditt. Når bufferen går til 512 bytes, så tvangsdroppes data for å klarere buffer. Altså, systemet finner ikke stoppbit eller får ikke noen timeout
Slett ikke usannsynlig at telegramlengdene er forskjellig siden du har ett annet aggregat.

Du skriver du får lengder på 172, 173, 174. Antakelig er alle telegrammene like lange, men det er ustabil deteksjon av stopp som fører til at du får med +/- 1 telegram.
Siden jeg ikke har noen informasjon om hva som EGENTLIG er "end of telegram", så har jeg kun brukt strategien timeout, og satt verdien til 1 ms.
![image](https://user-images.githubusercontent.com/11056680/215879182-e0eb70c0-91b6-483b-86b7-5060f40a8253.png)

Det meste av data ligger i telegrammet som er ca. 177 bytes langt hos meg. Det er nok helt sikkert det samme som hos deg har 172-174 bytes. 
Hvis du prøver å ta ut statistikk, er det en lengde som utmerker seg som flest forekomster? Prøv å endre bufferSize i denne filtreringen:

```
if (header[0] == 0 && header[1] == 16 && bufferSize == 177) {
  topic = "FlexitCI50_StateReport";
```

Noden "primary parsing" er slett ikke elegant. Siden jeg ikke har noen informasjon om protokollen, så er jeg usikker på hvordan ting egentlig er "delt opp" fra Flexit sin side. Er det faste telegramlengder? Er det seperasjonskarakterer, er det spesifikke telegrammer? Har ikke anelse. Måten jeg har delt det opp er kun et desperat forsøk på å få det til å bli repeterbart.

Måten jeg har gjort det på er absolutt ikke stabil eller klar for produksjon. Jeg tenker en veldig viktig ting nå blir å dykke litt dypere for å få dette mer stabilt. Jeg har "slengere" hos meg også som avviker fra 177 bytes, og det er et absolutt tegn på at ikke alt er som det bør være. Flexit har jo også valgt seg en heftig hastighet på 115Kbaud, så her kan det også stå på hardware.

Kanskje du kommer til å oppleve større stabilitet med EW11. Hvilket adapter har du i dag?

**Comment by patstave** [comment]
I've made a new issue describing the software problems. Please feel free to open a new issue regarding hardware problems. Regarding the unstable buffer split you can comment in https://github.com/patstave/Node-FlexitCS60-RS485/issues/2
