### ISSUE TITLE
Ask for Flexit protocol documentation

### ISSUE THREAD

**Issue by patstave** [patstave/Node-FlexitCS60-RS485#3]
Can Flexit provide protocol documentation, if we ask very nicely... ?

**Comment by abdavid** [comment]
I had an email correspondence with Flexit today. They very elegantly pointed towards the manual for [CI66](https://www.flexit.no/globalassets/catalog/documents/man_111824no_3509.pdf) and the manual for [CS60](https://www.flexit.no/globalassets/catalog/documents/man_111036no_3364.pdf). No luck for now at least.

**Comment by patstave** [comment]
I've contacted head of development in Flexit Sweden. Fingers crossed, but i don't have huge hopes :)

**Comment by abdavid** [comment]
I asked ChatGPT to chip in 😆 

To decode a serial buffer where you do not know the RS485 registers, you can follow these steps:

1. Determine the baud rate, data bits, stop bits, and parity of the serial communication. You can use a logic analyzer or an oscilloscope to measure the timing of the communication.

2. Identify the format of the data in the buffer, such as ASCII or binary. This can be done by analyzing a sample of the data and looking for patterns or using a library to attempt to recognize the format.

3. Use a hex editor to inspect the contents of the buffer and try to understand the structure of the data. This may involve looking for header and footer patterns, or specific sequences of bytes that could represent commands or responses.

4. If the data format is ASCII, you can use a text editor to view the contents of the buffer and manually attempt to decode the data. If the data format is binary, you may need to write a custom program to decode the data, or use a library or tool that can read binary data formats.

Document your findings and repeat the process with additional data to verify your understanding of the data format and contents.

It is important to have a deep understanding of the communication protocol used by the device sending the data to be able to effectively decode the data. In some cases, you may need to reverse-engineer the protocol by analyzing the data and experimenting with different inputs to the device.

**Comment by patstave** [comment]
Flexit is not willing to provide docs
