### ISSUE TITLE
Packet offsets for the 179 packet

### ISSUE THREAD

**Issue by MSkjel** [patstave/Node-FlexitCS60-RS485#7]
Here is a list of the offsets I have currently found to the packet with length 179 for my UNI 3. This is by no means complete, and some of them might in fact be wrong. This packet is sent from the ventilation system controller to the CI600 as a kind of state report and should contain the majority of the data we are actually interesed in.  The offsets are from the start of the packet. All of the data in the packet also seem to be 16 bit. Feel free to add to this list :)

```
# These have to be divided by 10 to get temperature!
SETPOINT_AIR_TEMPERATURE_OFFSET = 7
SUPPLY_AIR_TEMPERATURE_OFFSET = 17
OUTDOOR_AIR_TEMPERATURE_OFFSET = 21

HEATER_ENABLED_OFFSET = 167
HEATER_PERCENTAGE_OFFSET = 29
HEAT_EXCHANGER_PERCENTAGE_OFFSET = 27

REGULATION_MODE_OFFSET = 9

# Enum for regulation modes
REGULTION_MODES = ("Stop", "Min", "Normal", "Max", "Max In")

ERROR_STATE_OFFSET = 20

SUPPLY_AIR_FAN_SPEED_PERCENT_OFFSET = 31
```

**Comment by patstave** [comment]
Great job MSkjel! Feel free to contribute to the code or add documentation to the repo! I think i have some of these in the flows.js code already, but not all. Again thank you

**Comment by MSkjel** [comment]
Welp, see #2
